#!/usr/bin/env python3.3
import sys
import os
import subprocess
import configparser


def call_port(arguments):
    """
    This function calls the port executable with the specified parameters,
    printing the output to stdout.
    """
    command = ["port"] + arguments
    if (os.getuid != 0):
        return subprocess.call(["sudo"] + command)
    else:
        return subprocess.call(command)


if __name__ == '__main__':
    conf = configparser.RawConfigParser()
    conf.read(os.path.expanduser('~/.config/port-wrapper'))
    params = sys.argv[1:]
    if params[0] in conf.options("Aliases"):
        params[0] = conf.get("Aliases", params[0])
    call_port(params)
